spring:
  datasource:
    url: jdbc:mysql://codeplus.ddns.net:3306/formare_db?createDatabaseIfNotExist=true
    username: root
    password: R@0t

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate-dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
    show-sql: true
#
#server:
#  error:
#    include-binding-errors: always
#    include-message: always
#  port: 8081
