spring:
  datasource:
    datasource1:
      url: jdbc:mysql://codeplus.ddns.net:3306/formare_db?seUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      username: root
      password: R@0t

    datasource2:
      url: jdbc:mysql://codeplus.ddns.net:3306/dtoschema?seUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      username: root
      password: R@0t
  jpa:
    datasource1:
      hibernate:
        ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate.format_sql: true
    datasource2:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate-dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate.format_sql: true
        show-sql: true
#
#    entityManagerFactory:
#      primary:
#        persistence-unit-name: primary
#      secondary:
#        persistence-unit-name: secondary
##main.allow-bean-definition: true
##
server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8080
